### ISSUE TITLE
Broken link on https://cloud.ibm.com/docs/hpc-spectrum-symphony?topic=hpc-spectrum-symphony-setting-up-api

### ISSUE THREAD

**Issue by jkarmiol** [ibm-cloud-docs/hpc-spectrum-symphony#1]
On [the IBM Cloud Docs / [IBM Spectrum Symphony](https://cloud.ibm.com/docs/hpc-spectrum-symphony) / Setting up the IBM Cloud Schematics API page](https://cloud.ibm.com/docs/hpc-spectrum-symphony?topic=hpc-spectrum-symphony-setting-up-api), clicking on the **Create a workspace** link send me to

[IBM Cloud Docs](https://cloud.ibm.com/docs/)
    [Page not found](https://cloud.ibm.com/docs/ibm-spectrum-symphony?topic=ibm-spectrum-symphony-creating-workspace#)

Documentation
Sorry, this content isn’t available.
It seems we can’t find what you’re looking for. Try the IBM Cloud Docs search to find information.

**Comment by mlgordon** [comment]
The broken link was fixed.
