### ISSUE TITLE
 'Create a workspace'  hyperlink is broken 

### ISSUE THREAD

**Issue by rodrigolara1** [ibm-cloud-docs/hpc-spectrum-symphony#2]
'Create a workspace'  hyperlink is broken 

https://cloud.ibm.com/docs/hpc-spectrum-symphony?topic=hpc-spectrum-symphony-setting-up-api

![image](https://user-images.githubusercontent.com/131889203/234608665-46a1dc66-96fa-4f8e-8c69-fa3c76727a3e.png)

![image](https://user-images.githubusercontent.com/131889203/234608181-658d1bf3-8351-4212-b670-1742dab3d65a.png)

**Comment by mlgordon** [comment]
Broken link was fixed.
