### ISSUE TITLE
'IBM Cloud Schematics CLI' hyperlink is broken 

### ISSUE THREAD

**Issue by rodrigolara1** [ibm-cloud-docs/hpc-spectrum-symphony#3]
'IBM Cloud Schematics CLI' hyperlink is broken 

https://cloud.ibm.com/docs/hpc-spectrum-symphony?topic=hpc-spectrum-symphony-setting-up-cli

![image](https://user-images.githubusercontent.com/131889203/234641120-27f5d4fa-13a0-478a-8044-b738cd8fcdcb.png)

![image](https://user-images.githubusercontent.com/131889203/234641623-c8e575e1-3c67-45ed-9fbf-41dcb2142a19.png)

**Comment by mlgordon** [comment]
Broken link was fixed.
