### ISSUE TITLE
Get the SSH command fixed for accessing the storage/compute nodes

### ISSUE THREAD

**Issue by alexarvinraj** [ibm-cloud-docs/hpc-spectrum-symphony#4]
1. Storage Nodes

- Section that needs to be fixed: https://cloud.ibm.com/docs/hpc-spectrum-symphony?topic=hpc-spectrum-symphony-accessing-gui&interface=ui#access-storage-cluster
- Existing content: 
ssh -L 22443:localhost:443 root@{STORAGE_NODE_IP_ADDRESS} root@{FLOATING_IP_ADDRESS}
- Corrected content:
ssh -L 22443:localhost:443 -J root@{FLOATING_IP_ADDRESS} root@{STORAGE_NODE_IP_ADDRESS}

2. Compute nodes
- Section that needs to be fixed: https://cloud.ibm.com/docs/hpc-spectrum-symphony?topic=hpc-spectrum-symphony-accessing-gui&interface=ui#access-compute-cluster
- Existing content: 
ssh -L 21443:localhost:443 root@{COMPUTE_NODE_IP_ADDRESS} root@{FLOATING_IP_ADDRESS}
- Corrected content:
ssh -L 22443:localhost:443 -J root@{FLOATING_IP_ADDRESS} root@{COMPUTE_NODE_IP_ADDRESS}

**Comment by alexarvinraj** [comment]
@mlgordon This is the minor update which was pointed out by one of our internal customer.

**Comment by mlgordon** [comment]
Content updated!
